# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: MSc Computing Individual Project
author: Barry Quek Jing Jet

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: project-experiments.tex

# TODO - Add a bibtex file so that I can create citations
# bibtex_bibfiles:
#   - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jjquek/indiv-project-exps  # Online location of your book

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
